### PR TITLE
add fieldResolver option

### PR DESCRIPTION
**Pull request by mhagmajer**
This solves issue https://github.com/graphql/express-graphql/issues/331

### CODE REVIEW

**Comment by mhagmajer** [comment]
Just signed the CLA

**Comment by mhagmajer** [comment]
@wincent can you kindly take a look at this please?

**Comment by digego** [comment]
Any chance we can get this change merged?

**Comment by mhagmajer** [comment]
@leebyron any chance you could help out here or point us in the right direction? Thanks

**Comment by vivex** [comment]
any update ?

**Comment by IvanGoncharov** [comment]
@mhagmajer @digego @vivex Merged 🎉 
Sorry for the delay.
I'm working on a new release and plan to publish it in the next few days.

**Comment by vivex** [comment]
@IvanGoncharov  when is new release expected ?

**Comment by IvanGoncharov** [comment]
@vivex ATM I'm very busy with `graphql-js@14.0.0` I will switch to this package afterward.

**Pull request merged**
