### PR TITLE
Relicense as MIT

### PR DESCRIPTION
**Pull request by treycordova**
In the spirit of @leebyron's relicensing of https://github.com/graphql/graphql-js/commit/4f5e351c2afb28e4ae3a44eae76d45d895ff3aa2, I'm putting forward a relicensing of express-graphql to MIT. This work mirrors his.

### CODE REVIEW

**Comment by junminstorage** [comment]
ping @IvanGoncharov here. This will increase the popularity of this repo

**Comment by IvanGoncharov** [comment]
@junminstorage I'm working on it:
https://github.com/graphql/graphql-wg/blob/master/notes/2018-06-14.md#licensing-issues-express-graphql-codemirror-graphql-graphiql-logo-ig-5m
Thanks for pinging me, it reminded me that I need to write the followup email.

**Comment by treycordova** [comment]
@IvanGoncharov, this PR has sat for two months. Any news?

**Comment by IvanGoncharov** [comment]
@treycordova Thanks for the ping 👍 
ATM I'm very busy with `graphql-js@14.0.0` release but Licensing issues are next in my list.

**Comment by treycordova** [comment]
@IvanGoncharov, the GraphQL working group is meeting on the 20th. Would it be helpful to join that meeting to talk about relicensing? I didn't see it on the list of topics.

**Comment by IvanGoncharov** [comment]
@treycordova Sorry for the delay. It was already discussed on the last WG.

And the next step it to compile a list of all similar issue from different repos + other OSS related tasks for which we need something from Facebook. Over last few months I was busy with `graphql-js@14.0.0` release but now it's shipped I will try to compile it, this week.

**Comment by leebyron** [comment]
Unfortunately relicensing issues need to be routed through Facebook's legal team and happens one project at a time. I'm working on tracking this with my existing contacts at Facebook - note that recently GraphiQL was relicensed as MIT!

Thanks for your patience

**Comment by AGS-** [comment]
@leebyron Let me follow up on this tomorrow.

**Comment by treycordova** [comment]
@AGS-, how are things moving along inside Facebook? Any updates?

**Comment by AGS-** [comment]
Nothing to announce yet, let me follow up.

**Comment by kaelzhang** [comment]
Years have been passed. Any updates?

**Comment by IvanGoncharov** [comment]
@kaelzhang All core projects (including `express-graphql`) are in process of migration to the newly formed GraphQL Foundation.
So I expect the license will be changed after all legal formalities will be done.

**Comment by IvanGoncharov** [comment]
I switched license in #515 + removed license headers from source files.
Thanks for the patience.

**Pull request closed without merging**
