### PR TITLE
[incremental-delivery]: Remove the content-length requirement

### PR DESCRIPTION
**Pull request by maraisr**
This removes the need for `Content-Length`, and handles the boundaries such that the next boundary is flushed as soon as possible.

References:
- https://github.com/graphql/graphql-over-http/pull/152
- fmg https://github.com/relay-tools/fetch-multipart-graphql/pull/22
- [meros](https://github.com/maraisr/meros)

cc @robrichard

### CODE REVIEW

**Review by robrichard — APPROVED** [review]

**Comment by acao** [comment]
@maraisr if you could fix the prettier issue, then we can merge!

**Comment by maraisr** [comment]
This has been fixed @acao

**Comment by acao** [comment]
image

last thing seems to be this failing unit test

**Comment by robrichard** [comment]
@acao I think this is a flaky test in the base branch. If it's ok I can merge this and fix it there?

**Comment by acao** [comment]
for sure!

**Pull request merged**
