### PR TITLE
Support passing a promise as the schema option

### PR DESCRIPTION
**Pull request by sorenbs**
I need to load the schema from a database based on request headers. As far as I can figure there is no way to do this currently. In this pr I support passing a promise to the schema option. Is this a good approach?

### CODE REVIEW

**Comment by leebyron** [comment]
Schema is retrieved from Options which is already a function of the request. Is there any reason you can't use that existing mechanism?

```js
app.use(urlString(), graphqlHTTP(req => {
  return {
    schema: req.header.fooBar ? SchemaOne : SchemaTwo,
  };
}));
```

**Comment by sorenbs** [comment]
Thanks Lee

I need to fetch the schema from a database. My initial thought was to wrap options in a promise like this:

```
app.use(urlString(), graphqlHTTP(req => {
  return getSchema(req).then(schema => {
    return {
      schema: schema,
    };
  });
}));
```

But graphqlHTTP expects options to be an object, not a promise.

My workaround is to have an extra middleware that retrieves the schema and sticks it on the request like this:

```
app.use(urlString(), (req, res, next) => {
  getSchema(req)
  .then(schema => {
    req.schema = schema;
    next();
  })
});

app.use(urlString(), graphqlHTTP(req => {
    return {
      schema: req.schema,
    };
}));
```

This works but is a little clunky.

**Comment by leebyron** [comment]
That makes sense! I've added this capability now

**Comment by sorenbs** [comment]
Thanks!

**Pull request closed without merging**
