### PR TITLE
Add support for errorsCallback so we got errors detail on server …

### PR DESCRIPTION
**Pull request by ohardy**
I added a test for this but sinon must be used for this test to really work. Didn't know if you are OK to include sinon and sinon-chai ?

### CODE REVIEW

**Comment by leebyron** [comment]
Two primary points of feedback:

First, please ensure this change is well scoped. This makes some seemingly unrelated changes to the package.json file.

Second, could you help me understand the motivation for this change? This seems directionally good, but I'd like to better understand what you're trying to accomplish by proposing this, since there may be other solutions to consider.

**Comment by leebyron** [comment]
Also please see and mirror existing test formatting rather than including new test mechanisms

**Comment by cdonohue** [comment]
This could be extremely helpful.

If `graphql` is hooked up to a database to make a query, wouldn't you want to intercept any errors and handle them accordingly? Currently, you are only able to format the errors, which passes them in a `200` response with the errors inside an `errors` property.

And, when promises are used, every request will go through as a success _unless_ there is a `graphql` [syntax error](https://github.com/graphql/express-graphql/blob/master/src/index.js#L142), [wrong verb used](https://github.com/graphql/express-graphql/blob/master/src/index.js#L160), etc.

So, in database example above, How would one go about sending back anything other than a `200`?

**Comment by cdonohue** [comment]
@leebyron @ohardy ?

**Comment by ohardy** [comment]
@cdonohue For me it's OK now with `formatError`, not you ?

**Comment by cdonohue** [comment]
I guess I'm just looking for a solution where errors can be caught _and_ the response be set accordingly.

Take the example above. If the graphql backend is connected to a database and for some reason, the database is down (problem outside of graphql). When the graphql query/mutation returns, it will still send a `200` status back to the client. You can format the errors all you want, but you are still dealing with a `SUCCESS`.

This also means that you would have to handle your client requests a bit differently for `express-graphql`:
```js
axios.post("/path-to-graphql", { query, variables })
  .then(response => {
    if (response.data.errors && response.data.errors.length) {
      throw response.data.errors[0];
    }
    // --> process data
  })
  .catch(error => {
    // handle client errors
  })
;
```

To me, the `catch` should do it's job _without_ having to check `response.data.errors' and throw accordingly.

Maybe this should go in its own issue? But I already saw that https://github.com/graphql/express-graphql/issues/36 has been closed out.

How are others handling this case when errors happen on the server and `200` status codes are being sent?

**Comment by leebyron** [comment]
Returning 200 is intentional in the case that a nullable portion of a query failed, but other parts of the request succeeded. Express-graphql should return an error code if the whole query fails

**Comment by cdonohue** [comment]
Thanks for clarifying, @leebyron. I'll revisit my example and double-check everything.

**Comment by leebyron** [comment]
Closing this as I think we have better solutions for the two motivating examples:

1. You wish to format error output before they get to the client. Options can include a `formatError` function which does exactly this.
2. You wish to log errors as they occur for metrics purposes. express-graphql is probably the wrong layer of abstraction to do such a thing, this isn't implemented yet, but there is a tracking task for this very purpose at https://github.com/graphql/graphql-js/issues/284.

**Pull request closed without merging**
