### PR TITLE
Support graphql-ws client for GraphiQL IDE

### PR DESCRIPTION
**Pull request by junminstorage**
To follow up #687 and continue to address #390, I drafted this PR to 
- [x] add support for https://github.com/enisdenjo/graphql-ws client for GraphiQL IDE.
- [x] upgrade subscription-transport-ws to its latest version
- [x] add example server startup script of using graphql-ws for subscription support
- [x] add example server startup script of using subscriptions-transport-ws for subscription support
- [x] use fetcher from https://github.com/graphql/graphiql

Questions:
~~1. There is no umd version of graphql parser, e.g. graphql-tag publish a umd parser but it has dependency on graphql itself. I use a simple regex to check if the graphQLParams contains subscription operation. Options:
    - wait for https://github.com/graphql/graphiql/pull/1770 to finish so we can use its umd fetcher which supports both ws clients
    - create umd fetcher or graphql parser in this repo.~~
2. developer provides ```websocketClient``` as part of ```graphiql``` option, its values are "v0" for subscriptions-transport-ws, "v1" for graphql-ws, I did this based on graphile/postgraphile#1338, open to better naming suggestion. 

Specifically check out this tutorial script about how to start web socket server to support subscription using enisdenjo/graphql-ws : https://github.com/junminstorage/graphql-tutorial/blob/master/src/index_v1.js

### CODE REVIEW

**Comment by acao** [comment]
hey this is awesome!

just wanted to point out that this is in the works as well:
https://github.com/graphql/graphiql/pull/1770

we were hoping to publish this library alongside GraphiQL, and then here we can use that utility to generate the fetcher as well. what do you think?

**Comment by junminstorage** [comment]
That will be perfect! Note the apollographql/GraphiQL-Subscriptions-Fetcher is already archived and doesn't work for https://github.com/enisdenjo/graphql-ws, so to have a generic and up-to-dated fetcher will be great!

**Comment by acao** [comment]
@junminstorage to be honest, it should never have ended up in this repo. i had asked someone to use the subsriptions fetcher as prior art to build something new and they installed the package directly, haha! oops!

**Comment by junminstorage** [comment]
@acao I looked at your great work on @graphiql/create-fetcher in graphql/graphiql#1770, it seems you are very close to finish line. It is big PR, do you have any ETA? I wonder if it is worth creating a dedicated PR for fetcher related changes.

**Comment by acao** [comment]
@junminstorage hey thank you! i hope to finish it by tomorrow

**Comment by acao** [comment]
@junminstorage forgot to update you, you should be good to pull in `@graphiql/create-fetcher` and get that set up!

**Comment by junminstorage** [comment]
@achao I run into issue with the ```@graphiql/create-fetcher```, see this issue: https://github.com/graphql/graphiql/issues/1800 please help.

Also another question, you provide https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/docs/create-fetcher.md#wsclient option for developer to inject graphql-ws client dependency, could you provide another option for developer to inject subscriptions-transport-ws as well. This allows graphiql/toolkit not tied to any particular versions of both clients.

**Comment by acao** [comment]
it was a matter of significant debate to even get `subscriptions-transport-ws` into this utility, so we may need to revisit that since `graphql-ws` is being worked into the official transport spec, whereas `subscriptions-transport-ws` is abandoned and has a deprecation notice.

we are about to publish it under `@graphiql/toolkit` as an RC, since we don't need a seperate package, and then release 0.1.0, so it will be `import { createFetcher } from '@graphiql/toolkit'` next release

**Comment by junminstorage** [comment]
@acao all changes are ready! 
But I missed up my commit id in this PR draft and will recreate new branch and new PR with correct username.

**Comment by junminstorage** [comment]
replaced by #755

**Pull request closed without merging**
