### PR TITLE
update graphql peerdep

### PR DESCRIPTION
**Pull request by graingert**
This is a fixed version of https://github.com/graphql/express-graphql/pull/407

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@graingert Great 👍 
Can you also fix `npm test`?
Updating `flow-bin` will solve all Flow errors.
You also need to update error messages inside tests:
https://travis-ci.org/graphql/express-graphql/jobs/329899395#L827

**Comment by graingert** [comment]
Was hoping it would just pass. Will have a fiddle locally

**Comment by graingert** [comment]
@IvanGoncharov I also had to update eslint.

**Comment by graingert** [comment]
@IvanGoncharov can you also have a look at my other PRs: https://github.com/graphql/express-graphql/pull/410 https://github.com/graphql/express-graphql/pull/409

**Comment by IvanGoncharov** [comment]
@graingert Great 👍
Now we need to wait for someone with commit rights to merge this PR.

@leebyron Can you please take a look?

**Comment by IvanGoncharov** [comment]
@leebyron This is super simple PR that just add support for `^0.12.0` vesions of `graphql-js` and fix a few test. At the same time it blocks a lot of people including myself from upgrading to the new version of `graphql`.
Can you please take a look?

**Comment by IvanGoncharov** [comment]
@leebyron Now that `0.13` is published can you please merge this PR and also add `0.13` to peerDependencies?

Without this change `express-graphql` is unusable 😭

**Comment by IvanGoncharov** [comment]
@graingert Merged 🎉  Thank you for PR and sorry for the delay. 
I will try to make release ASAP.

**Comment by graingert** [comment]
Woops this is a bit too late 0.13 came out.

**Comment by IvanGoncharov** [comment]
@graingert I'm working on it.
I just got commits rights to this repo so I want to make a new release including all simple PRs.

**Comment by graingert** [comment]
Kay

**Comment by graingert** [comment]
Any chance of a graphql monorepo? So versions can be updated and tested in
lockstep?

**Comment by IvanGoncharov** [comment]
@graingert It's planned to release `graphql@14.0.0`, so updating peer dependency will be required only after breaking changes: https://github.com/graphql/graphql-js/issues/1005

**Comment by IvanGoncharov** [comment]
@graingert 📦 `v0.6.12` released with support for graphql v0.12.x and v0.13.x.

**Pull request merged**
