### PR TITLE
Make dependencies up-to-date, needed to fix bug: https://phabricator.babeljs.io/T2212

### PR DESCRIPTION
**Pull request by bkinsey808**
So, I ran into an issue with the dist/index.js file. I was trying to consume this project as a dependency in a typescript project.  Apparently the older version of babel was incorrectly inserting

```
module.exports = exports["default"]
```

into the compiled code, which was causing this issue: https://github.com/Microsoft/TypeScript/issues/5565

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by bkinsey808** [comment]
I am struggling trying to get mocha to work with babel 6. Sorry about the mess of commits. Still have not found a solution. Can anybody help?

**Comment by bkinsey808** [comment]
Asked for help on a mocha forum: https://groups.google.com/forum/#!topic/mochajs/sywjRY2WqKc

**Comment by leebyron** [comment]
I backed out the changes to supertest and supertest-as-promised and then tests passed. My guess is that supertest changed the way that testing interface works in a breaking way.

**Comment by leebyron** [comment]
Merged in 900b91760dd1e7997889e9026ec559d605c28b5e

**Pull request closed without merging**
