### PR TITLE
Allow formatError to be a promise

### PR DESCRIPTION
**Pull request by arunv**
Summary:
Often we need do so some datafetching (even from cache) to properly annotate the error.

Also useful if you want to log errors server-side to anything but the console output.

Test Plan:
First ran npm run test

Added the following route to the server:

When an error is thrown intentionally, we can see the "abe to process promises" logged. 
app.use(
  '/graphql',
  expressGraphQL(req => ({
    schema,
    graphiql: __DEV__,
    rootValue: { request: req },
    pretty: __DEV__,
    formatError: async function(error) {
          let ret = await testAsync();
          console.log(ret);
        return {
          working: 1,
          error: error,
        };
     }
  })),
);

async function testAsync() {
  return "able to process promises";
}

### CODE REVIEW

**Comment by arunv** [comment]
Ah, I'm going to close this PR because the problem has been addressed. 

The proper way to solve this is:

app.use('/graphql', graphqlHTTP(async (request, response, graphQLParams) => ({
  schema: MyGraphQLSchema,
  rootValue: await someFunctionToGetRootValue(request)
  graphiql: true
})));

**Comment by PatrLind** [comment]
I am not sure I understand the proper way of doing it as @arunv is suggesting.
The PR is about `formatError` to be able to take an async function, but the response seems not to to be about this at all?

**Comment by arunv** [comment]
@PatrLind Since `formatError` is a property on an object that is returned by the function passed to graphqlHTTP, you can make that function be async. 

So, in my example what is happening is:

```
app.use('/graphql', expressGraphQL(req => ({ 
  schema, 
  graphiql: true, 
  formatError: formatErrorFn 
  /* .. etc etc ...*/
})))
```

This is the same as:

```
app.use('/graphql', expressGraphQL(req => {
return { 
  schema, 
  graphiql: true, 
  formatError: formatErrorFn 
  /* .. etc etc ...*/
};
})))
```
This is the same as:

```
app.use('/graphql', expressGraphQL(function(req) {
return { 
  schema, 
  graphiql: true, 
  formatError: formatErrorFn 
  /* .. etc etc ...*/
};
})))
```

Now all you have to do is convert this function into an async function

```
app.use('/graphql', expressGraphQL(async function(req) {
return { 
  schema, 
  graphiql: true, 
  formatError: formatErrorFn 
  /* .. etc etc ...*/
};
})))
```
Now that it's an async function, you can await another async function inside of it

```
app.use('/graphql', expressGraphQL(async function(req) {
return { 
  schema, 
  graphiql: true, 
  formatError: await asyncFormatErrorFn(req),
  /* .. etc etc ...*/
};
})))
```

**Comment by PatrLind** [comment]
@arunv Thanks for the suggestion, however, I am not sure I understand how this will solve the problem.
If I await like you suggest, that awaits the function pointer, not the processed error. The error processing still needs to be done synchronously. Right?
It seems to be that your original PR would have fixed this issue.

**Pull request closed without merging**
