### PR TITLE
fix: Allow empty operation names for single queries

### PR DESCRIPTION
**Pull request by flovilmart**
Fixes issue #767

### CODE REVIEW

**Comment by flovilmart** [comment]
@saihaj or @acao ,  sorry to ping you here, any chance we can move forward with this patch?

**Comment by saihaj** [comment]
I can’t merge this in but @IvanGoncharov can cut a release for this.

**Comment by IvanGoncharov** [comment]
@flovilmart Did you report this issue to `graphql-go`?
GraphQL spec doesn't have any special treatment for the empty string as `operationName`: https://spec.graphql.org/draft/#sec-Executing-Requests
So I don't think it's appropriate to merge this PR.

**Comment by flovilmart** [comment]
Thanks @IvanGoncharov, after reading the spec, it seems that the go implementation is indeed not following the specification regarding empty operation names.

I’ve raised the issue here: https://github.com/graphql-go/graphql/issues/616

**Pull request closed without merging**
