### PR TITLE
Revert "Allow custom handling of runtime query errors"

### PR DESCRIPTION
**Pull request by acao**
Reverts graphql/express-graphql#696

we have to be following the transport spec error codes:

https://github.com/graphql/graphql-over-http/blob/master/spec/GraphQLOverHTTP.md#status-codes

### CODE REVIEW

**Comment by MatthiasKunnen** [comment]
How does #696 violate the linked spec?

**Comment by meleyal** [comment]
The [current version of the spec](https://github.com/graphql/graphql-over-http/blob/40a50a351a887799b3d1550b665b2101b26dcda4/spec/GraphQLOverHTTP.md#status-codes) doesn't mention returning 500s, can this be reverted?

**Comment by joshribakoff-sm** [comment]
I believe the authors of the library are misreading the spec:

> If the GraphQL response contains the {data} entry and it is {null}, then the server SHOULD reply with a 2xx status code and it is RECOMMENDED it replies with 200 status code.

My response contains a null data entry as described, and yet it still corrupts the status code.

Can we revert this?

**Comment by mihairadulescu** [comment]
Apollo-Client cannot be used with the 500 status code !!!!!!!!!! FIX THIS ASAP!

**Pull request merged**
