### PR TITLE
enable arrow-parens, update babel-eslint@4.0.10

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by leebyron** [comment]
Awesome, thanks @hzoo!

**Comment by leebyron** [comment]
Aww, I merged too soon. Unfortunately we're still seeing the issues with "require parens"

**Comment by hzoo** [comment]
Weird.. thought I tested locally and passed - will investigate..

**Comment by leebyron** [comment]
https://travis-ci.org/graphql/express-graphql/jobs/76371390 shows the failure

**Comment by hzoo** [comment]
Ok wow... I know why now - I had to make that rule in eslint-plugin-babel since I can't edit the actual eslint rule.

**Pull request merged**
