### PR TITLE
auto prettify

### PR DESCRIPTION
**Pull request by rybon**
Based on #508 this time.

### CODE REVIEW

**Comment by rybon** [comment]
@IvanGoncharov how about this approach?

**Comment by IvanGoncharov** [comment]
@rybon It feels more like a workaround. I don't want to maintain GraphiQL customization especially since GraphiQL maintainers planning big redesign effort for `1.0.0`.

To better understand your use case can you please provide more details. Is it public or private API? Why having `Prettify` button is not enough in your case?

**Comment by rybon** [comment]
This does the same thing as the `Prettify` button, only automatically if `autoPrettify` is enabled in the `options` object. It does not require any changes to GraphiQL in this case. It makes use of the existing public API of GraphiQL.
It only affects the public API of this project on an opt-in basis.

**Comment by IvanGoncharov** [comment]
> Basically, this feature is a small ergonomic improvement to perform that click for you.

How about adding a keyboard shortcut?
I think it will be supported by GraphiQL maintainers.

**Comment by rybon** [comment]
There is a keyboard shortcut. But this happens server-side, before the page is loaded so just opening the URL is enough.

**Comment by IvanGoncharov** [comment]
@rybon Thanks for the PR but I don't think `express-graphql` should be in the business of modifying GraphiQL behavior.

I'm open to generic things like passing options or listing additional GraphiQL plugins (after GraphiQL `1.0.0`) but I don't think the `express-graphql` should a place where you customize GraphiQL.

**Pull request closed without merging**
