### PR TITLE
feat: upgrade graphiql to 0.17.5

### PR DESCRIPTION
**Pull request by acao**
bumping the graphiql implementation from 0.14.2 to 0.17.5.
lockfile includes requisite bumps to dependencies

(update: remove node 8 from travis config)

### CODE REVIEW

**Comment by acao** [comment]
ah so graphiql requires node 9.7 or greater

https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/
node 8 is no longer supported this year at all. so I'll update the PR to bump the version in travis, or just create another PR?

**Comment by danielrearden** [comment]
Should the `engines` property in package.json also be updated to reflect dropping support for node 8?

**Comment by acao** [comment]
well, the engine dependency is now not strict which makes this easier

it can just inherit the warning from graphiql itself, but i guess we could add the engines value here too. just no strict

**Comment by danielrearden** [comment]
@acao @IvanGoncharov With #614 merged, we could close this but there's still the question of removing Node 8 from the Travis config

**Comment by IvanGoncharov** [comment]
@danielrearden Thanks for the ping 👍 
I plan to sync this repo as much as possible with `graphql-js` including GitHub actions set up so I will do that today and it has only currently supported node versions in it.

**Pull request closed without merging**
