### PR TITLE
Extensions function receives raw query param

### PR DESCRIPTION
**Pull request by eladitzhakian**
Following @nodkz 's suggestion [here](https://github.com/graphql/express-graphql/issues/197#issuecomment-274791235) (and also, I really need this 😄 )

### CODE REVIEW

**Comment by asiandrummer** [comment]
@eladitzhakian we should able to get the query string by printing the document AST (`print(ast)`) - would that suffice your use case?

**Comment by eladitzhakian** [comment]
@asiandrummer It would work, and it's not the only workaround as the query string is also available via the `req` variable, but I still believe it belongs in a dedicated arg

**Comment by leebyron** [comment]
Hey @eladitzhakian, sorry for the wait. #302 now ensures that this value is available for all options including extensions - however you will need to refer to the value provided in the options function - does that work for you?

**Comment by eladitzhakian** [comment]
@leebyron sure, thanks

**Pull request closed without merging**
