### PR TITLE
Implementation of features from #75

### PR DESCRIPTION
**Pull request by calebmer**
This PR contains a couple of new features (because it is easier to open one PR instead of a bunch of PRs with dependencies on one another). This contains an implementation of features from #75 and the small GraphiQL changes I made in #73.

A full list of changes is as follows:

- Updating of the eslint config (using the config from [graphql/graphql-js](https://github/graphql/graphql-js) as I assume they are one in the same).
- Support for any node server framework which supports connect style middleware.
- Feature for production servers which disallows clients sending `query` parameters instead using `operationName` and a predefined GraphQL document.
- Documentation for these features.

With these changes `express-graphql` will no longer only support `express`, so it would be nice to see the project renamed to `graphql-http` representing its polymorphism over HTTP server frameworks. If desired I can also create `./hapi.js` and `./koa.js` files for interoperability with these frameworks.

GraphQL is awesome, let's give it awesome server tooling 👍

### CODE REVIEW

**Comment by calebmer** [comment]
Do you know why tests are failing on `iojs` and `0.12`? I can't reproduce these errors locally…

**Comment by calebmer** [comment]
\cc @leebyron

**Comment by leebyron** [comment]
Could you figure out how to break this into independent PRs? This is great work, but keeping changes small and scoped will be easier to review and easier to find any intermediate breakages

**Comment by calebmer** [comment]
Ok, it's a little more work for me. Expect a couple of PRs after some cherry picking.

**Comment by calebmer** [comment]
@leebyron split up all the PRs into #81, #82, #83, #84, and #85. I'll be fixing tests I missed as they pop up on CI in case I missed it locally 😖

When the issue I couldn't debug is isolated I'll mention it.

**Pull request closed without merging**
